{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name:  {{ .Values.env }}-{{ .Values.petclinic.name }}-ingress
  namespace: prod
  annotations:    
    kubernetes.io/ingress.class: nginx    
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.spring.context_path | quote }}
        backend:
          serviceName: {{ .Values.env }}-petclinic-svc
          servicePort: 80
{{- end }}