apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env }}-{{ .Values.petclinic.name }}-svc
  namespace: {{ .Values.env }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Values.env }}-{{ .Values.petclinic.name }}
    env: {{ .Values.env }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.petclinic.targetPort }}
      name: {{ .Values.petclinic.name }}-port
